# File: .github/workflows/repo-sync.yml
name: sync- danwangshimoluo -scripts
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ main ]
  repository_dispatch:
    types: sync- danwangshimoluo -scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync  danwangshimoluo -scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/danwangshimoluo/JdScripts.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}
name: update_list


on:
  workflow_dispatch:
  #schedule:
    #- cron: '1 5,17 * * *'
  repository_dispatch:
    types: update_list
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}

      - name: "更新Readme中脚本清单列表"
        run: |
          bash update_list.sh
      - name: commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name lxk0301
          git add .
          git commit -m "更新Readme中脚本清单列表 by lxk0301 Github Action" -a || echo "Nothing to update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: master
